#!/bin/bash

cd /sys/devices/system/cpu  # a virtual directory made visible by device drivers
newSpeedTop=`awk '{print $1}' ./cpu0/cpufreq/scaling_available_frequencies`
newSpeedLow=$newSpeedTop  # make them the same in this example
for c in ./cpu[0-9]* ; do
    echo "current speed"
   cat ${c}/cpufreq/scaling_max_freq
   cat ${c}/cpufreq/scaling_min_freq

    echo "cranking up CPU $c to $newSpeedTop"
echo "performance" > ${c}/cpufreq/scaling_governor
   echo $newSpeedTop >${c}/cpufreq/scaling_max_freq
   echo $newSpeedLow >${c}/cpufreq/scaling_min_freq
   cat ${c}/cpufreq/scaling_max_freq
   cat ${c}/cpufreq/scaling_min_freq
cat ${c}/cpufreq/scaling_governor
 done

