#!/bin/bash
# base ceph template will be registered - localhost.localdomain
# 8.4 with perl installed
# on the network with 192.168.56.250

if [ "$1" == "" ]; then
    echo "usage :  update-ceph <template: rhel79|rhel84_rhel86> <new name> <new ip>"
    echo "usage :  update-ceph cloned <new name> <new ip> -- for manually cloned vm"
    exit;
fi
if [ "$1" != "cloned" ]; then

    #first param will be the template name
    case "$1" in
        "rhel79")
            template=rhel79-template
        ;;
        "rhel84")
            template=rhel84-template
        ;;
        "rhel86")
            template=rhel86-template
            ;;
        *)
            echo "Unknown template $1"
            exit;
        ;;
    esac


    # validate $1
    virsh list --all |grep template |grep $1 > /dev/null
    if [ "$?" == "1" ]; then
        echo "Template $1 does not exist. Templates should have dashes and not _"
        exit
    fi

    echo $2 |grep '_' > /dev/null
    if [ "$?" == "0" ]; then
        echo "destination VM names should have dashes and not _"
        exit
    fi

    echo "clone template $template to $2"
    clonevm  $template $2
    sleep 10

    echo "Starting clone $2"
    virsh start $2
    sleep 60

else

    grep $2 /etc/hosts > /dev/null
    if [ "$?" == "1" ]; then
        echo "Please add $2 to /etc/hosts manually first"
        exit;
    else
        echo "skipping the cloning, using already cloned vm $2"
    fi

    virsh list |grep $2 |grep running
    if [ "$?" == "1" ];  then
        echo "Starting clone $2"
        virsh start $2
        sleep 60
    fi

fi

# run this script
ssh-keygen -R "ceph-template"
ssh-copy-id -f -o StrictHostKeyChecking=no  ceph-template
echo "Changing hostname to $2"
# change the hostname
ssh ceph-template hostname
ssh ceph-template hostnamectl set-hostname $2.example.com
ssh ceph-template hostname


if [ "$1" != "cloned" ]; then
    echo "$3 $2.example.com $2" | sudo tee -a /etc/hosts
    IP=$3
else
    echo "skipping adding $2 to hosts"
    IP=$(grep $2 /etc/hosts |awk '{print $1}')
fi
# change the IP address
echo changing IP to $IP
ssh ceph-template perl -i -p -e "s/192.168.56.250/$IP/g" /etc/sysconfig/network-scripts/ifcfg-e*0
ssh ceph-template reboot

# after reboot with hostname reset, reregister
# create the baseline snapshot in virt-manager
# subscription-manager register --force


# turn off grub quiet mode
#ssh ceph4-admin  "cat /etc/default/grub |sed 's/rhgb quiet//g' > /tmp/grub; mv /tmp/grub /etc/default/grub; grub2-mkconfig -o /boot/grub2/grub.cfg"

# RHEL7
#subscription-manager register --force --username=glaw@redhat.com --password='1210W!llis' ; subscription-manager attach --pool=8a85f99c766234df01768d8228ba661b;
# for admin:
#  subscription-manager repos --enable=rhel-7-server-rhceph-4-tools-rpms --enable=rhel-7-server-ansible-2.9-rpms
# for i in rhcs4-rhel79-admin rhcs4-rhel79-node01 rhcs4-rhel79-node02 rhcs4-rhel79-node03; do echo $i; ssh root@$i "subscription-manager register --force --username=glaw@redhat.com --password=""1210W\!llis"" ; subscription-manager attach --pool=8a85f99c766234df01768d8228ba661b;"; done



# for monitor/osd :
#subscription-manager repos --enable=rhel-7-server-rhceph-4-mon-rpms ; subscription-manager repos --enable=rhel-7-server-rhceph-4-osd-rpms ; subscription-manager repos --enable=rhel-7-server-rhceph-4-tools-rpms
# need extras for docker install
#[glaw@fedora ~]$ ssh ceph4-79-node02 subscription-manager repos --enable=rhel-7-server-optional-rpms
#[glaw@fedora ~]$ ssh ceph4-79-node02 subscription-manager repos --enable=rhel-7-server-extras-rpms
#[glaw@fedora ~]$ ssh ceph4-79-node02 yum -y install docker device-mapper-libs device-mapper-event-libs
#[glaw@fedora ~]$ ssh ceph4-79-node02 "systemctl enable --now docker; reboot"

# grab ceph-ansible hosts, all.yml, osds.yml, etc from rhel8  --





# RHEL8

# base sub
#   56  subscription-manager attach --pool=8a85f99c7d76f2fd017d96c345750657
#
# developer sub 8a85f99c7990923e0179d3dcc315005b
## ceph ceph
# subscription-manager register --force --username=glaw@redhat.com --password='1210W!llis' ; subscription-manager attach --pool=8a85f99c766234df01768d8228ba661b; dnf config-manager --add-repo=ftp://partners.redhat.com/d960e6f2052ade028fa16dfc24a827f5/rhel-8/Tools/x86_64/os/; subscription-manager repos --enable ansible-2.8-for-rhel-8-x86_64-rpms ; yum -y install git ansible podman
#
#[root@ceph-mon01]# git clone https://github.com/ceph/cephadm-ansible.git


# ceph4 install --  on 8.4 -- ansible is older .. need to specify certain version
#[root@ceph4-admin ~]# subscription-manager repos --enable rhceph-4-tools-for-rhel-8-x86_64-rpms
#[root@ceph4-admin ~]# yum search --showduplicates ceph-ansible
#[root@ceph4-admin ~]# yum -y install ceph-ansible-4.0.31-1.el8cp.noarch


# firewall
# [glaw@fedora ~]$ ssh ceph4-node03 "systemctl stop firewall;systemctl disable firewalld"
# and option in all.yml

# install ceph-common on the admin node for mgmt
